/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:41bc72a4-65f6-495a-ac1a-d8247fdc0a9b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_l4uLUdPmJ",
    "aws_user_pools_web_client_id": "5hmpfmiq3n87njjkb7k8thvtkt",
    "oauth": {}
};


export default awsmobile;
