/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:41bc72a4-65f6-495a-ac1a-d8247fdc0a9b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_l4uLUdPmJ",
    "aws_user_pools_web_client_id": "5hmpfmiq3n87njjkb7k8thvtkt",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://2xygvk7b4bhvteimqoq54ejlfq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3y5bjtdghfflrlyn4skesnkbcu"
};


export default awsmobile;
